path:
  dataset:
    data:
      NIPS: NIPS_test
      KonIQ-10k: KonIQ-10k/1024x768
    labels:
      KonIQ-10k: data/KonIQ-10kinfo.mat

  save:
    ckpt: ckpt
    results: reslts_csv

train:
  epochs: 30
  lr: 0.0001
  