dataset:
  data:
    NIPS: "./NIPS_test"
    KonIQ-10k: /home/maindev/28i_mel/mnt/KonIQ-10k/1024x768
  labels:
    KonIQ-10k: /home/maindev/28i_mel/Linearity/data/KonIQ-10kinfo.mat

save:
  ckpt: /home/maindev/28i_mel/mnt
  results: "/home/28i_mel@lab.graphicon.ru/mnt/dione/28i_mel/Linearity-results"