
dataset:
  data:
    NIPS: "./NIPS_test"
    KonIQ-10k: "./dataset/KonIQ-10k/1024x768"
  labels:
    KonIQ-10k: "./dataset/KonIQ-10k/koniq10k_scores_and_distributions.csv"

save:
  ckpt: "/home/28i_mel@lab.graphicon.ru/mnt/dione/28i_mel/KonCept-ckpt"
  results: "/home/28i_mel@lab.graphicon.ru/mnt/dione/28i_mel/KonCept-results"