checkpoints:
  adversarial: "./chackpoints/adversarial_trained/resnet50_imagenet_linf_4.pt"
  texture: "./checkpoints/style_transfer_checkpoints/res50-texture-biased.pth"
  shape: "./checkpoints/style_transfer_checkpoints/res50-shape-biased.pth"
  debiased: "./checkpoints/style_transfer_checkpoints/res50-debiased.pth"

dataset:
  data:
    KonIQ: "./KonIQ-10k"
    NIPS: "./NIPS_test"
  labels:
    KonIQ: "./data/KonIQ-10kinfo.mat"