# Default parameters for training DBCNN
label_strategy: origin
perc: no
eval_only: yes
seed: 5102023
checkpoint_path: null
fc_model: ./fc_model
db_model: ./db_model
results_path: csv

options:
  activation: relu
  cayley1: false
  cayley2: false
  cayley3: false
  cayley4: false
  backbone: vgg16
  fc: false
  prune: 0.0
  prune_lr: 0.00001
  prune_epochs: 15
  prune_type: l1

data:
  dataset: KonIQ-10k
  scnn_root: pretrained_scnn/scnn.pkl
  data_info: mnt/KonIQ-10k/koniq10k_distributions_sets.csv
  directory: mnt/KonIQ-10k/1024x768

test_data:
  NIPS: 
    directory: mnt/NIPS
  KonIQ-10k:
    data_info: mnt/KonIQ-10k/koniq10k_distributions_sets.csv
    directory: mnt/KonIQ-10k/1024x768

log:
  directory: ./checkpoints/dbcnn1024

lr_scheduler:
  type: multistep
  milestones: [ 1000 ]
  gamma: 1.0

train:
  lr: 0.0001
  weight_decay: 0.0005
  epochs: 50
  num_workers: 4
  batch_size: 8
  val_criterion: PLCC
  gr: false

attack:
  path:
    checkpoints: mnt/DBCNN-activation=relu.pth
  train:
    type: none
  test:
    -
      type: pgd
      params:
        eps: 2.0
        alpha: 2.5
        iters: 1
        mode: zero
    -
      type: pgd
      params:
        eps: 4.0
        alpha: 5.0
        iters: 1
        mode: zero
    -
      type: pgd
      params:
        eps: 6.0
        alpha: 7.5
        iters: 1
        mode: zero
    -
      type: pgd
      params:
        eps: 8.0
        alpha: 10.0
        iters: 1
        mode: zero
    -
      type: pgd
      params:
        eps: 10.0
        alpha: 12.5
        iters: 1
        mode: zero
