attack:
  path:
    checkpoints: mnt/DBCNN-backbone|vgg16-gr-activation|Felu.pth
  test:
  - params:
      alpha: 2.5
      eps: 2.0
      iters: 1
      mode: zero
    type: pgd
  - params:
      alpha: 5.0
      eps: 4.0
      iters: 1
      mode: zero
    type: pgd
  - params:
      alpha: 7.5
      eps: 6.0
      iters: 1
      mode: zero
    type: pgd
  - params:
      alpha: 10.0
      eps: 8.0
      iters: 1
      mode: zero
    type: pgd
  - params:
      alpha: 12.5
      eps: 10.0
      iters: 1
      mode: zero
    type: pgd
  train:
    type: none
checkpoint_path: null
data:
  data_info: mnt/KonIQ-10k/koniq10k_distributions_sets.csv
  dataset: KonIQ-10k
  directory: mnt/KonIQ-10k/1024x768
  scnn_root: pretrained_scnn/scnn.pkl
db_model: mnt/DBCNN-backbone|vgg16-gr-activation|Felu.pth
eval_only: false
fc_model: fc_model/DBCNN-backbone|vgg16-gr-activation|Felu.pkl
label_strategy: origin
log:
  directory: checkpoints/dbcnn1024
lr_scheduler:
  gamma: 1.0
  milestones:
  - 1000
  type: multistep
options:
  activation: Felu
  backbone: vgg16
  cayley1: false
  cayley2: false
  cayley3: false
  cayley4: false
  fc: true
  prune: 0
  prune_epochs: 1
  prune_lr: 1.0e-05
  prune_type: l1
perc: false
seed: 5102023
train:
  batch_size: 8
  epochs: 1
  gr: true
  lr: 0.00001
  num_workers: 4
  val_criterion: PLCC
  weight_decay: 0.0005
